export const projectDetails = {
  finanza: { name:'Finanza', status:'ativo', date:'18 mai 2026', iso:'2026-05-18', change:'Ajustado o layout do gráfico mensal.', tech:['Kotlin','JavaScript','HTML/CSS'], summary:'Controle financeiro pessoal para vencimentos, listas, importações e decisões do dia a dia.', github:'https://github.com/Jeffersonf/finanza', pc:'C:\\Users\\jeffe\\finanza' },
  finanzav3: { name:'Finanza v3', status:'legado vivo', date:'18 mai 2026', iso:'2026-05-18', change:'A versão de referência recebeu os últimos ajustes do gráfico mensal.', tech:['JavaScript','HTML/CSS','SQL'], summary:'Versão anterior do Finanza preservada como referência de produto, código e ideias.', github:'https://github.com/Jeffersonf/finanza', pc:'C:\\Users\\jeffe\\finanzav3' },
  finfit: { name:'Finfit', status:'em construção', date:'18 mai 2026', iso:'2026-05-18', change:'Refinado o plano semanal e restaurada a presença da navegação.', tech:['JavaScript','HTML/CSS','PWA'], summary:'Organização de treinos, saúde e acompanhamento pessoal em um fluxo direto.', github:'https://github.com/Jeffersonf/finfit', pc:'C:\\Users\\jeffe\\finfit' },
  finvita: { name:'Finvita', status:'em construção', date:'26 abr 2026', iso:'2026-04-26', change:'Frontend e backend foram consolidados em uma única base.', tech:['Java','JavaScript','Android'], summary:'Rotina, cuidado e informações pessoais conectados ao ecossistema de ferramentas.', github:'https://github.com/Jeffersonf/finvita', pc:'C:\\Users\\jeffe\\finvita' },
  painelure2: { name:'Painel URE2', status:'em uso', date:'04 ago 2026', iso:'2026-08-04', change:'Notificações passaram a ser fechadas automaticamente.', tech:['JavaScript','Node.js','HTML/CSS'], summary:'Painel operacional para dados, acompanhamento e organização do trabalho da URE.', github:'https://github.com/Jeffersonf/painelure', pc:'C:\\Users\\jeffe\\painelure2' },
  setechub: { name:'Setec Hub', status:'em construção', date:'11 ago 2026', iso:'2026-08-11', change:'Atualizados os dados do agendamento de veículos.', tech:['JavaScript','Node.js','Supabase'], summary:'Hub para centralizar informações, processos e ferramentas da área técnica.', github:'https://github.com/Jeffersonf/painelurelegado', pc:'C:\\Users\\jeffe\\setechub' },
  bandamarcial: { name:'Banda Marcial', status:'em construção', date:'25 mai 2026', iso:'2026-05-25', change:'Atualizadas as fotos e o comportamento dos modais.', tech:['TypeScript','React','CSS'], summary:'Presença digital e organização do conteúdo, história e atividades da banda.', github:'https://github.com/Jeffersonf/banda-marcial', pc:'C:\\Users\\jeffe\\bandamarcial\\banda-marcial' },
  arena: { name:'Arena Futevôlei', status:'ativo', date:'24 jun 2026', iso:'2026-06-24', change:'Removidas camadas CSS redundantes para simplificar a interface.', tech:['JavaScript','Node.js','PWA'], summary:'Gestão de alunos, aulas, presenças, pagamentos e recados para escola de futevôlei.', github:'https://github.com/Jeffersonf/arena-futvolei', pc:'C:\\Users\\jeffe\\arena-futvolei' },
  jeffef: { name:'jeffef.dev', status:'caderno aberto', date:'11 ago 2026', iso:'2026-08-11', change:'Corrigida a abertura dos projetos locais a partir do painel.', tech:['Astro','TypeScript','CSS'], summary:'Caderno pessoal com notas, cenas, contexto e uma visão viva dos projetos.', github:'https://github.com/Jeffersonf/jeffef', pc:'C:\\Users\\jeffe\\jeffef-site' },
  'finanza-next': { name:'Finanza Next', status:'ativo', date:'10 ago 2026', iso:'2026-08-10', change:'Avançada a paridade visual e funcional do aplicativo Android.', tech:['Kotlin','Android','Gradle'], summary:'Nova geração do ecossistema Finanza com Android nativo e módulo de viagens.', github:'https://github.com/Jeffersonf/finanza-next', pc:'C:\\Users\\jeffe\\finanza-next' },
  'finanza-android': { name:'Finanza Android Kotlin', status:'em desenvolvimento', date:'19 jul 2026', iso:'2026-07-19', change:'Adicionados testes de gestos de navegação no aplicativo.', tech:['Kotlin','Android','Gradle'], summary:'Implementação Android nativa do Finanza para evolução e paridade visual.', github:null, pc:'C:\\Users\\jeffe\\finanza-android-kotlin' },
  nexttrip: { name:'NextTrip', status:'protótipo', date:'11 ago 2026', iso:'2026-08-11', change:'O roadmap do aplicativo foi revisado e atualizado.', tech:['Kotlin','Android','Jetpack'], summary:'Aplicativo para planejar viagem, orçamento, roteiro e checklist.', github:null, pc:'C:\\Users\\jeffe\\nexttrip' },
  fisiosaas: { name:'FisioSaaS', status:'em construção', date:'23 abr 2026', iso:'2026-04-23', change:'Alinhado o sistema de listagem clínica.', tech:['HTML/CSS','JavaScript','Python'], summary:'Sistema SaaS com frontend web e backend Python.', github:'https://github.com/Jeffersonf/FisioSaaS', pc:'C:\\Users\\jeffe\\Downloads\\BarbeariaSaaS' },
  'automacao-confirmacao': { name:'Automação Confirmação', status:'local', date:'30 jun 2026', iso:'2026-06-30', change:'Atualizado o ambiente local usado para executar a automação.', tech:['Python'], summary:'Automação para agilizar confirmações e reduzir tarefas repetitivas.', github:null, pc:'C:\\Users\\jeffe\\Nova pasta (2)\\AutomacaoConfirmacao' },
  'robo-sam': { name:'Robô SAM', status:'local', date:'13 abr 2026', iso:'2026-04-13', change:'Atualizado o robô de automação de equipamentos.', tech:['Python'], summary:'Robô de automação mantido localmente com ambiente Python.', github:null, pc:'C:\\Users\\jeffe\\Downloads\\Robo SAM' },
  odysseus: { name:'Odysseus', status:'referência', date:'11 ago 2026', iso:'2026-08-11', change:'Corrigida colisão em escritas atômicas do núcleo.', tech:['Python','JavaScript','Node.js'], summary:'Projeto híbrido mantido localmente a partir de um repositório externo.', github:'https://github.com/pewdiepie-archdaemon/odysseus', pc:'C:\\Users\\jeffe\\odysseus\\odysseus' },
  sisteminha: { name:'Sisteminha', status:'arquivado', date:'21 mai 2025', iso:'2025-05-21', change:'Conteúdo do projeto foi atualizado.', tech:['TypeScript'], summary:'Experimento TypeScript preservado como parte do histórico.', github:'https://github.com/Jeffersonf/sisteminha', pc:null },
  'agua-poke': { name:'Água Poke', status:'arquivado', date:'05 mai 2025', iso:'2025-05-05', change:'Projeto local foi integrado ao README do GitHub.', tech:['Python'], summary:'Projeto experimental em Python preservado no GitHub.', github:'https://github.com/Jeffersonf/agua-poke', pc:null },
  portfolio: { name:'Portfólio', status:'legado', date:'23 abr 2025', iso:'2025-04-23', change:'Atualizado o conteúdo do portfólio.', tech:['TypeScript'], summary:'Versão anterior do portfólio pessoal.', github:'https://github.com/Jeffersonf/portfolio', pc:null },
  'cadastro-time': { name:'Cadastro Nosso Time', status:'privado', date:'01 out 2022', iso:'2022-10-01', change:'Removido o diretório antigo do formulário.', tech:['HTML/CSS'], summary:'Projeto privado de cadastro e interface mantido como referência.', github:'https://github.com/Jeffersonf/cadastro-nosso-time', pc:null },
  'formulario-cadastro': { name:'Formulário de Cadastro', status:'privado', date:'03 set 2022', iso:'2022-09-03', change:'Arquivos do formulário foram adicionados ao repositório.', tech:['HTML'], summary:'Formulário HTML de estudo preservado em repositório privado.', github:'https://github.com/Jeffersonf/formulario-de-cadastro', pc:null },
  'python-alura': { name:'Python Alura', status:'privado', date:'18 mar 2022', iso:'2022-03-18', change:'Notebooks e exercícios foram adicionados ao repositório.', tech:['Python','Jupyter Notebook'], summary:'Cadernos e exercícios da formação em Python.', github:'https://github.com/Jeffersonf/Python-Alura', pc:null },
  forgottenserver: { name:'Forgotten Server ORTS', status:'arquivo', date:'29 jul 2014', iso:'2014-07-29', change:'Corrigida a missão Demon Oak no servidor.', tech:['Lua','C++'], summary:'Fork histórico de servidor Open Tibia.', github:'https://github.com/Jeffersonf/FORGOTTENSERVER-ORTS', pc:null }
} as const;

export type ProjectId = keyof typeof projectDetails;

export const projectRoadmaps: Record<ProjectId, string[]> = {
  finanza:['Consolidar a experiência mobile','Refinar importações e relatórios','Ampliar testes e automações'],
  finanzav3:['Catalogar o que ainda vale migrar','Arquivar fluxos substituídos','Manter apenas correções essenciais'],
  finfit:['Definir o MVP','Criar rotina de treinos','Adicionar histórico e evolução'],
  finvita:['Unificar os fluxos principais','Melhorar a experiência mobile','Preparar uma versão estável'],
  painelure2:['Aprimorar indicadores','Simplificar rotinas recorrentes','Documentar operações críticas'],
  setechub:['Consolidar módulos prioritários','Revisar a migração de dados','Publicar a primeira versão estável'],
  bandamarcial:['Definir identidade e conteúdo','Construir páginas principais','Publicar a primeira versão'],
  arena:['Fechar o fluxo de pagamentos','Melhorar comunicação com alunos','Preparar implantação'],
  jeffef:['Evoluir a área de projetos','Ampliar o arquivo de notas','Refinar a publicação pelo CMS'],
  'finanza-next':['Consolidar módulos Android','Unificar dados com o Finanza','Preparar distribuição estável'],
  'finanza-android':['Concluir paridade com a versão web','Integrar sincronização','Gerar versão de distribuição'],
  nexttrip:['Conectar dados persistentes','Completar roteiro e despesas','Preparar primeira versão instalável'],
  fisiosaas:['Alinhar nome e domínio do produto','Consolidar o fluxo principal','Preparar implantação'],
  'automacao-confirmacao':['Documentar execução','Adicionar tratamento de falhas','Versionar no GitHub'],
  'robo-sam':['Revisar o fluxo atual','Documentar configuração','Criar repositório próprio'],
  odysseus:['Definir objetivo de uso','Registrar alterações próprias','Decidir entre fork ou referência'],
  sisteminha:['Documentar a proposta','Revisar dependências','Decidir se será retomado'],
  'agua-poke':['Adicionar documentação','Revisar funcionamento atual','Manter como arquivo ou retomar'],
  portfolio:['Preservar como referência','Migrar conteúdo relevante','Direcionar para o jeffef.dev'],
  'cadastro-time':['Documentar o exercício','Revisar acessibilidade','Arquivar ou incorporar ideias'],
  'formulario-cadastro':['Revisar validações','Adicionar estilos e acessibilidade','Manter como referência'],
  'python-alura':['Organizar por curso','Adicionar índice de conteúdos','Registrar aprendizados principais'],
  forgottenserver:['Manter como arquivo histórico','Documentar o contexto','Sem desenvolvimento ativo previsto']
};
